# Generated by Django 3.0.8 on 2020-07-09 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatcher_Register',
            fields=[
                ('idno', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Contact_Number', models.IntegerField(unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Details',
            fields=[
                ('Product_no', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=150)),
                ('Price', models.IntegerField()),
                ('Quality', models.CharField(max_length=150)),
                ('Add_Date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockerRegister',
            fields=[
                ('idn', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('contact_Number', models.IntegerField(unique=True)),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
    ]
