# Generated by Django 3.0.5 on 2020-07-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_details',
            name='Quantity',
            field=models.IntegerField(default=0),
        ),
    ]
